name: Module CI

on:
  push:
  workflow_dispatch:

jobs:
  tester:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

#      - name: Composer auth
#        run: |
#          echo 'COMPOSER_AUTH={"github-oauth":{"github.com":"'"${{ github.token }}"'"}}' >> $GITHUB_ENV
#          composer install --no-interaction --prefer-dist
#
#      - name: Install dependencies
#        run: composer install
#
#      - name: Install tester dependencies
#        run: |
#          cd vendor/bett-ingenieure/tester
#          composer install

      - name: Run tester
        run: php ./vendor/bett-ingenieure/tester/phptester.php
