name: Module CI

#on:
#  push:
#  workflow_dispatch:

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  tester:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer
          extensions: imagick, xdebug, swoole

      - name: Clone php build config
        run: git clone --depth 1 https://github.com/bett-ingenieure/php-build-config.git .php-build-config

      - name: Run php-build-config for PHP 8.2
        run: |
          php .php-build-config/php82-update.php

      - name: Install dependencies
        env:
          COMPOSER_AUTH: >
            {"github-oauth":{"github.com":"${{ secrets.COMPOSER_GH_TOKEN }}"}}
        run: |
          composer install --no-interaction --prefer-dist
          cd vendor/bett-ingenieure/tester
          composer install --no-interaction --prefer-dist

      - name: Run tester
        shell: bash
        env:
          TMPDIR: /tmp/
        run: |
          echo "PWD is: $PWD"
          echo "Running testerâ€¦"
          /opt/php-82/current-live/bin/php -d variables_order=EGPCS "$PWD/vendor/bett-ingenieure/tester/phptester.php"
          
          status=$?
          
          if [ $status -eq 0 ]; then
            echo "- Tests Passed"
          else
            echo "- Tests Failed"
            exit 1;
          fi

#      - name: Composer auth
#        run: |
#          echo 'COMPOSER_AUTH={"github-oauth":{"github.com":"'"${{ github.token }}"'"}}' >> $GITHUB_ENV
#          composer install --no-interaction --prefer-dist
#
#      - name: Install dependencies
#        run: composer install
#
#      - name: Install tester dependencies
#        run: |
#          cd vendor/bett-ingenieure/tester
#          composer install


