name: Module CI

on:
  push:
  workflow_dispatch:

jobs:
  tester:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Run tester
        shell: bash
        run: |
          echo "PWD is: $PWD"
          echo "Running testerâ€¦"
          ls -la vendor/bett-ingenieure/tester/vendor || true
          php -r 'echo "root autoload: ", file_exists("vendor/autoload.php") ? "yes\n":"no\n"; echo "tester autoload: ", file_exists("vendor/bett-ingenieure/tester/vendor/autoload.php") ? "yes\n":"no\n";'
          php -d variables_order=EGPCS "$PWD/vendor/bett-ingenieure/tester/phptester.php"

#      - name: Composer auth
#        run: |
#          echo 'COMPOSER_AUTH={"github-oauth":{"github.com":"'"${{ github.token }}"'"}}' >> $GITHUB_ENV
#          composer install --no-interaction --prefer-dist
#
#      - name: Install dependencies
#        run: composer install
#
#      - name: Install tester dependencies
#        run: |
#          cd vendor/bett-ingenieure/tester
#          composer install


