name: Module CI

on:
  push:
  workflow_dispatch:

jobs:
  tester:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer
          coverage: none

      - name: Checkout tester repo
        uses: actions/checkout@v4
        with:
          repository: bett-ingenieure/php-tester
          ref: main
          path: tester
          token: ${{ github.token }}

      - name: Install tester deps
        working-directory: tester
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run
        working-directory: ${{ github.workspace }}
        run: |
          echo "Target repo root: $(pwd)"
          echo "Tester repo path: $GITHUB_WORKSPACE/tester"
          ls -la "$GITHUB_WORKSPACE/tester" || true

          php "$GITHUB_WORKSPACE/tester/tester.php"
